---
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: {{ .Values.names.msname }}-{{ .Values.names.fename }}
  namespace: {{ .Values.nsname }}
spec:
  minReadySeconds: 5
  selector:
    matchLabels:
      app: {{ .Values.names.msname }}
      layer: {{ .Values.names.fename }}
  replicas: 2
  minReadySeconds: 5
  progressDeadlineSeconds: 300
  revisionHistoryLimit: 5
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
  template: 
    metadata:
      labels:
        app: mycart
        layer: frontend
    spec:
      containers:
      - name: mycart-frontend-container
        image: vniranjana/myapp-frontend:2.0
        imagePullPolicy: Always
        ports:
        - containerPort: 80
        resources:
          limits:
            cpu: {{ .Values.resource.frontend.cpu | quote }}
            memory: "500Mi"
          requests:
            cpu: "0.2"
            memory: "200Mi"
        env:
          - name: BACKENDLB
            value: backendapi
